### ISSUE TITLE
aggregate 0-t signatures, and aggregation of other signatures cannot be verified successfully

### ISSUE THREAD

**Issue by moonk98** [weavechain/threshold-sig#1]
Hello, I'd like to ask if I'm testing the library and find that it can only be signed by the 0-t nodes to be successfully verified. When I tested signatures from other nodes, they couldn't be successfully validated. Is the library currently only able to aggregate and verify 0-t signatures.

**Comment by weavechain** [comment]
Hello! Yes, it should support any configuration, just that you need to take care to use the corresponding R(i) and signature when you have a different configuration of nodes (while still using t Lagrange coefficients, but matching the indexes of the replying nodes).
Please check the latest commit, we've updated the test and made the functions easier to use by specifying the participating nodes. Also published a v1.1 of the jar.
